### ISSUE TITLE
Add Coventry Building Society

### ISSUE THREAD

**Issue by joshaw** [dumb-password-rules/dumb-password-rules#126]
Coventry Building Society in the UK, has to be between 6 and 10 characters, can't contain any punctuation and you have to give characters from it on the phone to confirm identity!

> Your password must be between 6 and 10 characters long and must not use spaces, commas or any other punctuation.

![Screen Shot 2019-07-31 at 18 41 29](https://user-images.githubusercontent.com/3018066/62234590-e2b43900-b3c2-11e9-9eed-d2d7daf5ee33.png)

Appologies, not able to create a PR.

**Comment by duffn** [comment]
Thanks, that's a pretty dumb one.

**Comment by JoshuaBehrens** [comment]
3 single characters to match a whole password... There must be a lot more off than just the text on the confirm button 😖

**Comment by duffn** [comment]
Would somebody like to open a PR for this?

**Comment by jmsv** [comment]
@duffn PR merged - issue can be closed
