### ISSUE TITLE
BMO has fixed their 6 character password limit

### ISSUE THREAD

**Issue by JoelB** [dumb-password-rules/dumb-password-rules#133]
See new password rules in attached image
![2019-09-05 19_59_14-BMO Bank of Montreal Online Banking](https://user-images.githubusercontent.com/99556/64391721-d8b3d480-d017-11e9-8877-bd77e91da62a.png)

**Comment by duffn** [comment]
Thanks. I'll happily accept PRs if you'd like to update the entry

**Comment by mittonface** [comment]
The original entry didn't even fully capture the stupidity of the BMO password system (which I recognize they have now fixed).

The most egregious part was *not* that your password had to be only 6 characters. It was that whatever password you chose ended up getting mapped to where those characters were on a telephone keypad. So, for example if your password was `passwo`, you were also able to login with `727796` or `rARsYo` or anything else that mapped to the same characters. 

I really should have switched banks when I found this out.

**Comment by duffn** [comment]
> So, for example if your password was passwo, you were also able to login with 727796 or rARsYo or anything else that mapped to the same characters.

That is absolutely unbelievable.

**Comment by duffn** [comment]
Closed by #254.
