### ISSUE TITLE
Add examples or rules for good password policies 

### ISSUE THREAD

**Issue by timvisee** [dumb-password-rules/dumb-password-rules#152]
I think adding a small section with rules for good password policies would be a great resource. What do you think?

**Comment by duffn** [comment]
I like that idea. I’ll happily review a PR if you want to take a crack at it.

**Comment by danehrlich1** [comment]
@timvisee Start with Google. 99 characters the last time I checked, and that was like 2 years ago...

**Comment by rillig** [comment]
Could this be a duplicate of #80?

**Comment by duffn** [comment]
Yes, I think this can be covered there. Thanks.
