### ISSUE TITLE
Bank of America 20 chars max + other dumb things

### ISSUE THREAD

**Issue by danehrlich1** [dumb-password-rules/dumb-password-rules#163]
Please see the below screenshot. 
![boa](https://user-images.githubusercontent.com/3357202/64428096-78a14a80-d078-11e9-97d8-cdd46129ae2c.png)

Also if you go to [this link](https://secure.bankofamerica.com/auth/forgot/reset-entry/) and then inspect the source code of the page (ctrl+f for the word "consecutive" and it should bring you to the right point) you can verify these requirements are still in force.

**Comment by danehrlich1** [comment]
Again anyone is free to take this and make their own PR or if not I will get around to it in a few days

**Comment by duffn** [comment]
@danehrlich1 Thanks for all the issues!
