### ISSUE TITLE
Chase Bank passwords

### ISSUE THREAD

**Issue by rorymurphy** [dumb-password-rules/dumb-password-rules#179]
Hi -

Could you re-validate the post regarding Chase? I work at JPMC (but not on that site) and was interested in tracking down the responsible team but the link no longer resolves and, just from what I see, appears that functionality may have been brought under the chase.com umbrella, whose passwords are most definitely case sensitive. Thanks -

Rory

**Comment by duffn** [comment]
Thanks for reaching out. That URL sends you to some "outage" page and I cannot find that login page any longer with the password rules. I will remove this entry.
