### ISSUE TITLE
Amex is case insensitive

### ISSUE THREAD

**Issue by marekr** [dumb-password-rules/dumb-password-rules#188]
I shit you not, they strtolower the input. Upper and lower character entropy be damned
Anyone can try this themselves trying to log in.

Also I have a vague recollection that they also silently truncate passwords as well.

**Comment by duffn** [comment]
Yep, they are terrible.

https://github.com/dumb-password-rules/dumb-password-rules#american-express
https://twitter.com/dumb_pw_rules/status/1170098726410412032
