### ISSUE TITLE
Is silent truncation sufficient?

### ISSUE THREAD

**Issue by bobpaul** [dumb-password-rules/dumb-password-rules#227]
I've seen a number of websites over the years that silently truncate passwords, either during login (but not during password change, making it impossible to login if you used a long password) or on the backend (which results in a silent loss of entropy, turning `correct horse battery staple` into the not very secure `correct hors`. As I dig these up, I'll submit them.

But I have one site that seems to have a decent password policy generally: min 6 chars, no other specific rules. Seems to accept all the special chars, spaces are ok. Seems to have an entropy check on the backend as short passwords are rejected unless they have lots of variation while all lowercase passphrases are just fine. BUT they truncate silently to 73 char. Is that sufficient to go on the list? A screenshot wouldn't show much as you can "have" a 120 char password and login with a 120 char password, but only the first 73 char matter.

**Comment by duffn** [comment]
I haven't made any specific rules to get on the list and 73 characters seems reasonably high to me, but I would definitely consider silently truncating enough for an entry.
