### ISSUE TITLE
AOL Comment misleading

### ISSUE THREAD

**Issue by ryanvanasse** [dumb-password-rules/dumb-password-rules#68]
In the section for AOL, it says

> Oh, and thanks for restricting one of the most common special characters!

However, the listed requirements don't appear to restrict any special characters? Rather, it _encourages_ the use of special characters `!@.#` saying

> Strong passwords include special characters (!@.#)

Limiting max length to 16 is still dumb but I'm not seeing any issues with special characters here.

**Comment by duffn** [comment]
Thanks for the note. I'm happy to take PRs if you'd like to reword that entry.
