### ISSUE TITLE
airasia, limited length and no special symbols can be taken. 

### ISSUE THREAD

**Issue by shirishag75** [dumb-password-rules/dumb-password-rules#73]
![airasia](https://user-images.githubusercontent.com/727626/34321436-13269788-e807-11e7-9f1d-06b8690721ba.png)

**Comment by duffn** [comment]
Great, thank you. Could you submit a PR with this screenshot and a small description per the README?

**Comment by shirishag75** [comment]
sorry, right now I'm on a windows box where git isn't set up otherwise would have done it. I would have to figure out git tools for MS-Windows and setting it up on MS-Windows would probably take a while. I tried to do it do the web-based way but for some reason it doesn't work. 

As far as the description is concerned,,  here it is - 

You can find it both in https://member.airasia.com/register.aspx?culture=en-GB or from resetting the password via e-mail/webmail 

The problems are there is a limit on length and no special symbols can be taken/used. 

I'm sharing the same when signing up which I'm also sending right now. 

![airasia2](https://user-images.githubusercontent.com/727626/34322219-c8d0dfdc-e819-11e7-83d0-13fb700cf6fb.jpg)
